server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/authorization'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: secret
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
keycloak:
  auth-server-url: 'http://localhost:8000/auth'
  realm: 'Authorization'
  resource: 'shop-app-client'
  public-client: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE